### ISSUE TITLE
Type of Quiz Quotes

### ISSUE THREAD

**Issue by twishasaraiya** [UdacityMobileWebScholarship/guess-quote#11]
Okay, so while giving the topic for collaborative projects I thought of book quotes since I read novels. But we could have it another way also. 

I would like to everyone's opinion on what type of quotes should be there in the quiz or whether there should be any type (just random quotes)???

**Comment by ashwani99** [comment]
I think there should be any type of quotes. Or rather why not let the user select based on his interests?

**Comment by twishasaraiya** [comment]
@ashwani99 We will not be having categories for now since the main idea was to dive deep into PWA. Due to time constraints, we will keep it simple for now.

We are developing our own API for storing questions and options.

**Comment by naveens239** [comment]
@twishasaraiya If its to gather quotes - general, books, miscellaneous - I can setup a document and input data with options. Let me know if I can take it up. I can gather 2 other folks to help me out here. 
How many questions are we planning in one go?

**Comment by twishasaraiya** [comment]
@naveens239 You can definitely take it up. But first we need to decide if it's going to be general quiz or not???  Also let me know who else is working with you on this?? 

In one go we can have 10 questions for the user.The database could have ,for now, 20-40 questions to start working with PWA. We can then simultaneously keep on adding more.

**Comment by twishasaraiya** [comment]
@naveens239, Yeah correct!! Let's keep it open to all kinds of quotes that are fun and interesting. Maybe we could have some quotes where we can have some nice cartoon animations would be nice.Dont you think so?? 
Other important issues for now are choosing audio files and start working on GreenSock.

**Comment by naveens239** [comment]
If its all cartoon animations - Awesome, but let's poll over that. Meanwhile about using pictures and especially audio files, let's make sure we collect only what is available for free and nothing that requires licensing.

**Comment by twishasaraiya** [comment]
#### Animations
We could definitely have a poll and decide because then we need to start sketching and designing the characters. 
#### Audio
I think we could open up a separate issue to discuss what audio would be suitable for a particular situation. I have shared the *Task List* on the slack channel which explains what kind of audio files we are looking for. I am currently searching for some small sized files which are freely available and suitable for our project.

**Comment by skarthikeyan96** [comment]
@naveens239, I can help you with gathering quotes

**Comment by naveens239** [comment]
@skarthikeyan96 Great. Let me first put up a poll to decide this front !

**Comment by twishasaraiya** [comment]
@parmeet1402 we will be using GreenSock for animations. If you are familiar with it great. If not you can start going through some tutorials.

**Comment by gpalsingh** [comment]
Let's remember that the focus should be implementing a working service worker before the deadline (14th May) so that we can demonstrate that we learned well from the course. It makes sense to keep the other features simple.

So I suggest we use simple text quotes for now without worrying about what they belong to. All the advanced and/or extra features can be added after the first phase ends.

**Comment by twishasaraiya** [comment]
Since most of the people have voted for general questions I am closing this issue here.Thank you, everyone, for your participation.
