### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by twishasaraiya** [UdacityMobileWebScholarship/guess-quote#12]
Design an eye-catching landing page for the project.
### Requirements
* Bright colorful scheme
* Background Animations

I have gone through *GreenSock Examples* and here are some I really liked 
* http://www.caribana-festival.ch/en/
* https://www.duroc.ma/en/
* https://interview.ueno.co/
 
These can be taken as reference for developing the landing page design.Please feel free to share your design here or on slack channel(don't forget to create a thraed for uploaded image there) to get feedback. 

Please let me know if you have any queries.

**Comment by twishasaraiya** [comment]
@smriti548 please free to share your idea here. Have you created any wireframes ??

**Comment by smriti548** [comment]
I don't have any wireframes... I just have the imagination of the idea and that is:
What if as the page opens different quotes(any general quotes) just come to the page from every side and form a particular pattern or the logo of the quote app... we can make the logo accordingly.

**Comment by twishasaraiya** [comment]
I may be wrong but if I have imagined correctly it would look good with small words rather than sentences(quotes here). Please correct me if I am wrong. 
 I rather prefer some shapes (like circles) or color changes. Have you gone through the reference UI design I have shared?? What do you think about them??

**Comment by parmeet1402** [comment]
My idea for the landing page is to have a random bright colour (From _flatui's colour palette_)  background. A random quote would be present under the play game/ start game button. The quote would have a **_typing effect_**. When a user would click on start game button the quote's text  would change into asterisks(*) and the game would start. 
So this is my idea for the landing page and I have created a wireframe for the same on this link ->  https://wireframe.cc/QKazeR . Hope you like the idea and feel free to tell some improvements that could be done.

**Comment by twishasaraiya** [comment]
@parmeet1402 I think it would be better if we move the discussion to slack channel so that everybody can give in their feedback. Please add your idea there and start a thread by addressing @Twisha. I would like to discuss the background of the page there.

**Comment by twishasaraiya** [comment]
That's cool @Sahil-Dhawan. Would look great but how do you plan on implementing it??? Since we are using GreenSock, this is could be done using that.
I am a beginner in Greenock and this is what I have created so far https://codepen.io/Twisha/full/rvOgGV/.
Please Let me know what you think. Actually, there is a lot of scope for improvement but this is something very basic I created.

**Comment by Sahil-Dhawan** [comment]
@twishasaraiya its nice had a look , I'll find some implementations and exemplar approach for the same till Saturday , I'll keep you posted regarding that , I'm sure this can be made pretty interactive and enticing.. My apologies for the late response

**Comment by blenderskool** [comment]
So I have made a design for Desktop and Mobile. **Since I don't know UI animation, I have kept the designs static, but they can be easily animated later**. I haven't seen the finalized logo or the color scheme, hence the design is completely on my own ideas. Do share your thoughts with me :slightly_smiling_face: 

Keeping the whole idea of a game, I have decided to not clutter the landing page, and allow the users to directly play the game.

![Desktop Landing Page](https://user-images.githubusercontent.com/21107799/39757056-410fd7ac-52e9-11e8-846f-11a27b144c5f.png)
![Mobile Landing Page](https://user-images.githubusercontent.com/21107799/39757057-4146124a-52e9-11e8-8f22-f21dd2553e83.png)

**Comment by ayushdev** [comment]
@blenderskool The design looks good. You can start the coding. We can tweak it as we go long.

**Comment by blenderskool** [comment]
@ayushdev Thanks, I am still not sure where and how will we include the logo of the project in my design, hence would wait for some more suggestions :slightly_smiling_face:

**Comment by twishasaraiya** [comment]
@blenderskool The design looks amazing. 👍  We have finalized the logo, you can have a look at it on the **slack channel (#cp_quote_app)**. Also since our color scheme uses shades of purple/violet I think we could change the green color here. 

Yes your idea of allowing the users to play the game directly is correct, that's what we will be doing. Also instead of **Top Players** we could add **Login** Option or remove it completely since this will be a single player game for now.

Let me what you think.

Once this is done you can start with the implementation. I could help with the UI animation if you are doing it on CodePen or any other online sites or we could add it later after the static site is ready. That shouldn't be a problem.

**Comment by twishasaraiya** [comment]
@blenderskool I would say whichever looks better go with that one.

**Comment by Sahil-Dhawan** [comment]
@twishasaraiya  https://iohk.io/ have a look at this website and move around your mouse a bit this was what I was talking about but couldn't understand how to exactly implement it

**Comment by Sahil-Dhawan** [comment]
The background here is dynamic as I was saying

**Comment by Sahil-Dhawan** [comment]
yes lets implement something like this for later :smile: @twishasaraiya

**Comment by twishasaraiya** [comment]
Yes definetely.

**Comment by twishasaraiya** [comment]
Completed #81 . Hence closing this issue.  Can be opened again for further enhancements if required in future.
