### ISSUE TITLE
Let's add eslint for the server code

### ISSUE THREAD

**Issue by skyshader** [UdacityMobileWebScholarship/guess-quote#15]
I see pull requests with multiple coding style violations in server side code base. My thoughts is to add eslint and configure it as per any recommended standard out there. Let's discuss the possibilities.

**Comment by ashwani99** [comment]
Agree with @anantoghosh but I don't think GitHub supports pre-commit hooks. A better solution might be to use CI for checking the linting. It will do the testing for us before PR is merged

**Comment by skyshader** [comment]
@anantoghosh would you submit the PR with eslint + prettier config in the root repo. Also, do configure `husky` for setting up pre-commit hook.

See the package.json file of this repository: https://github.com/UdacityMobileWebScholarship/just-notes

@anantoghosh pre-commit hooks are local hooks and are not related to github in any way.

**Comment by anantoghosh** [comment]
@skyshader I'll submit a PR

**Comment by skyshader** [comment]
@anantoghosh awesome. Keep us posted. :+1:

**Comment by anantoghosh** [comment]
Here's the thing, husky requires the `.git` folder in the same place as `package.json`.  
https://github.com/typicode/husky/blob/dev/docs.md#sub-directory-package

I'll have to add husky on the root `package.json` and then we can configure for both client and server.
Is this fine? @skyshader

**Comment by skyshader** [comment]
Yep. You're on the right track :+1:
