### ISSUE TITLE
Readme description

### ISSUE THREAD

**Issue by smriti548** [UdacityMobileWebScholarship/guess-quote#16]
I guess the readme file just contains very less introduction to the app. There should be some more description about the app for what it is being made or what it will do along with a user guide as well.

**Comment by twishasaraiya** [comment]
@smriti548 I think I have mentioned that it is being made for *Google Udacity Challenge Scholarship*. Also what exactly do you mean by user guide??? I am a little confused here. Could you please elaborate more.

**Comment by smriti548** [comment]
A user guide here means for the end users how they will use the app with a description of every feature. Actually, I have made some projects before with openmrs so I observed it there that every project must contain a user guide... No issues we could do that once we have completed the project 👍

**Comment by twishasaraiya** [comment]
@smriti548 I think we can close the issue here. We can open it once we have added some features to the project.
