### ISSUE TITLE
Dotenv module to load sensitive info (Feature Requirement)

### ISSUE THREAD

**Issue by charlie1404** [UdacityMobileWebScholarship/guess-quote#30]
### Description
Need a .env file from which one could load sensitive data like DB credentials of encryption keys etc. also NODE_ENVIRONMENT env variable should set to production when deploying, and this file needs to be added to .gitignore.

**Comment by skyshader** [comment]
Yes @charlie1404 that's planned and you will have it soon. Will keep everyone posted on this thread. Thanks for bringing this up.

**Comment by VarunDevPro** [comment]
We're reviewing the pull request #34 for now
