### ISSUE TITLE
API Creation

### ISSUE THREAD

**Issue by twishasaraiya** [UdacityMobileWebScholarship/guess-quote#36]
I can think of the following
- GET Quote and OPTIONS
-  UPDATE Score

Please let us know your suggestions here.

**Comment by danivijay** [comment]
What about fetching quote and options together? Like GET Question?? @twishasaraiya

**Comment by anurag-majumdar** [comment]
Truth is, our MongoDB schema will be somewhat like:
questions: [
{
   question: "...",
   options: ["....", ""..."],
   answer: ["..."]
},
// Continues
]

So during fetching of each of the questions, there will be requirement of just one GET request as @danivijay mentioned. Regarding the customizing of options as @twishasaraiya once told me, if there are 6 options we can use a random option generator function to generate random options (3 of them) from the options list and add the answer as a default to it to make it 4 options.

Let me know what you guys think regarding this?

**Comment by ashwani99** [comment]
I agree with @anurag-majumdar I will suggest a minor change to the schema
```json
questions: [
    {
        question: "...",
        answer: "..."  
    },
    ...
],
options: [
    'optionone',
    'optiontwo',
    ...
]
```
To keep things simple, we can process the GET `/question` as:
- Randomly choose a question, store its identifier so that it's not repeated again in a single game
- We will get 1 right answer, rest 3 can be chosen at random from the `options` list
- package all of them in a JSON and send it as response

**Comment by skyshader** [comment]
@anurag-majumdar Sure, take it on. Thanks again for contributing. :)

**Comment by ashwani99** [comment]
@skyshader I want to work on the API using ExpressJS. May I take that? I will work with @anurag-majumdar

**Comment by anurag-majumdar** [comment]
@ashwani99 Sounds great. You will be making changes to the route request and adding controllers I guess?

**Comment by ashwani99** [comment]
@anurag-majumdar Yes

**Comment by skyshader** [comment]
@ashwani99 do submit your own PRs. Note that working on something with dependencies needs a lot of collaboration and merges :)

So what I understand is:
@anurag-majumdar is taking up the schema creation for Quotes model.
@ashwani99 is taking up API creation for getting the quotes (This is tricky, lets discuss this further)

Some of the concerns while creating the API is:
1. One question per request
2. Random questions
2. Can't be repeated unless all options are exhausted.

Let's discuss.

**Comment by skyshader** [comment]
@sounak07 You can take UserAnswers which would contain user, the question they answered and if they were right or wrong with a score. Let's discuss this in a separate issue thread. Right now we are talking about schema creation. We will move to API next.

**Comment by SevenSinS02** [comment]
Yeah, I'd like to take something up as well... been away for a couple of days.

**Comment by skyshader** [comment]
@SevenSinS02 and others, please ask the questions not related to issues on slack channel. Let's keep the issues with relevant discussions.

**Comment by ashwani99** [comment]
@skyshader Nice points. So my suggestions will go like this:
1. Not necessarily. We can send a query param which will send us that many questions. Or rather make it a constant if the number of questions are same for every game. 
2. I didn't understand this concern. Can you please elaborate?
3. Options can get repeated. I see no issue with this. If you're concerned about same option coming again and again in a game, we can rectify it by adding more options. We can even make another layer by storing those options in chunks, so while choosing a set of options, we can just pick one from each chunk

**Comment by skyshader** [comment]
@ashwani99 
1. Number of questions are fixed to one. We will be having one question per screen.
2. These questions will not come in same order if I play again.
3. I meant if I attempted a certain question I don't want it to repeat for a significant amount of questions. Because if questions are random, it can appear just next or after one question.

**Comment by ashwani99** [comment]
@skyshader 
1. So I think we're good with this. One question per request.
2. As picking question will be done randomly, it's unlikely that this scenario will happen. We can add more questions to negate this scenario.
3. Okay so what we can do is generate a set of identifiers for the questions like `id`. We will have `/questions?limit=<number-of-questions` which will return a list of ids of questions chosen at random. Then for each question we will make `/quote/<id>` which will return us the `question`, `answer` and the `options`

**Comment by anurag-majumdar** [comment]
I am adding the schema in a new file in develop branch. Will send a PR soon.

**Comment by twishasaraiya** [comment]
@skyshader and @ashwani99 This is how I have thought about it. Suppose each question is of 100 points, I would like to continue the game till the user reaches 1000 points(If the user gets first 10 question right he wins) else the game continues till he reaches 1000 points. The user can leave the game at any point if he wishes too.
Let me know what you guys think.

**Comment by twishasaraiya** [comment]
@ashwani99 I think we should allow the user to select his target in the number of points(like a goal) he wishes to achieve instead of number of questions.

**Comment by anurag-majumdar** [comment]
@danivijay @twishasaraiya @skyshader Added a pull request for the question model file.

**Comment by ashwani99** [comment]
@anurag-majumdar I would suggest please move the discussion regarding the DB model to another issue

**Comment by skyshader** [comment]
So since we have the basic schema ready, i think we should start looking into the API bit.

Please acknowledge who is taking up the task and let's get started with the development :)

**Comment by anurag-majumdar** [comment]
I would like to contribute to one of the routes setup for API with schema. @skyshader

**Comment by VinayV9** [comment]
i liked to work on backend part is their any features left to do?? @twishasaraiya  @skyshader

**Comment by ashwani99** [comment]
@skyshader I wanted to take the API creation part https://github.com/UdacityMobileWebScholarship/guess-quote/issues/36#issuecomment-383617589
May I take this?

**Comment by skyshader** [comment]
Yes, @ashwani99 @anurag-majumdar take it away. Do comment which API you guys will be working on down below. :)

**Comment by anurag-majumdar** [comment]
@skyshader @ashwani99 I think we need to setup a route for questions in server.
Can I work on setting up the routes for the question part? Then @ashwani99 can work on the API GET /questions part.

Or we can negotiate on the both.

**Comment by suhasbansude** [comment]
What about UPDATE Score??
I think we need new collection for Score Details.

**Comment by skyshader** [comment]
The API for getting random set of questions is done and we are planning to keep the scoring offline for now. Hence closing this.
