### ISSUE TITLE
Logo Design Challenge

### ISSUE THREAD

**Issue by twishasaraiya** [UdacityMobileWebScholarship/guess-quote#7]
We would love to have an amazing logo for our project. As a part of this challenge, you can make a huge contribution to the project by designing the logo.

### How It Works
* You can DM the logo directly to me or any of the co-moderators along with your(or team) slack handle.
* Provide a brief description of the elements you chose and why.
* Once we have received all the logos we will be starting a poll. The logo with maximum points will get to be 
* You can make an animated logo as well.

_We will be adding all the logos received here so that your contributions can be counted_
**Deadline: Next Sunday(29th April)**

### Rules
1. You can work alone or in a team(max 2-4 people)
2. Do not post your logo designs on the slack channel because we don't want your ideas to be copied and moreover we need to keep the clutter minimum.
3. Only one entry per person or team will be allowed

Your feedback and suggestions are always most Welcome!!! Please clear any queries you have here before beginning.

**Note:** *If you have any creative ideas, you are free to use them as well. We just need a clean and attractive logo.*

**Comment by naveens239** [comment]
Is the name for this app fixed? Guess the Quote?

**Comment by twishasaraiya** [comment]
Yes mostly.

**Comment by 94151** [comment]
I would like to work on this.

**Comment by twishasaraiya** [comment]
@94151 Please go ahead. DM me the logo when you are done.

**Comment by twishasaraiya** [comment]
@94151 How's your work on logo design going on?? If you have any queries please feel free to reach out to me.

**Comment by twishasaraiya** [comment]
@Sahil-Dhawan Please feel free to DM me anytime. If you want, we could also open up a thread on the channel so that everybody can give in their suggestions.

**Comment by Sahil-Dhawan** [comment]
@twishasaraiya sorry for the late reply got caught up in internals I'll DM you with some logo suggestions by Friday as and when my internal practicals are done 😊

**Comment by twishasaraiya** [comment]
@Sahil-Dhawan Not a problem. Make sure you send me logo designs by Friday. 😃
