### ISSUE TITLE
Implementing authentication

### ISSUE THREAD

**Issue by danivijay** [UdacityMobileWebScholarship/guess-quote#8]
Please comment opinions and interest in contribution about implementing authentication with JWT.

**Comment by sounak07** [comment]
I would like to contribute jwt anthenticattion if assigned...

**Comment by sounak07** [comment]
Can we use mongoose to set up db?

**Comment by skyshader** [comment]
I think @danivijay is working on the database setup part.

Since you've shown interest towards working on jwt authentication, I'd say go ahead with it :+1: 

Just acknowledge with a response if you're taking this up. :)

**Comment by sounak07** [comment]
Yes I would take JWT then @skyshader

**Comment by danivijay** [comment]
Please let us know when will you  complete, so that the task can be assigned to you @sounak07

**Comment by drenther** [comment]
Will there be OAuth based Social auths or just local password based authentication?

**Comment by sounak07** [comment]
I think we should first implement local password based auth then we can extend it to Google, Facebook as alternative auth.

**Comment by drenther** [comment]
Sounds good. What about the Cookies vs LocalStorage? What is everyone's opinion on that?

**Comment by skyshader** [comment]
@sounak07 we can also look at only Google/Facebook (any one) in the beginning. @twishasaraiya @danivijay what are your thoughts? Do we want the users to create an account and then login with their username and password. Or do we just want them to get authenticated by maybe login using google or facebook?

**Comment by skyshader** [comment]
@drenther how is localstorage not a safest option. Any pointers?

**Comment by drenther** [comment]
Any JWT or info stored in localStorage is vulnerable to XSS. Take a look at this - https://www.rdegges.com/2018/please-stop-using-local-storage/

**Comment by twishasaraiya** [comment]
I think we should provide Google/Facebook login in the beginning then later on provide username and password login.

**Comment by SevenSinS02** [comment]
It's not really hard to implement cookies, especially with a ton of libraries already present.

**Comment by skyshader** [comment]
@drenther So, XSS happens when you allow the user to input malicious code to your application. We are anyway going to sanitize all the inputs we take from user before using it to interact with database (local or remote). This is similar case as it was with SQL injection. But people didn't throw SQL away instead they adhered to certain practices that takes care of such issues.

If we start searching about security issues with cookies we would find a ton of them. But it's how we handle user input at every place is what matters.

In my opinion we should go with localstorage. Do share your thoughts on above points. Would love to hear your point of view. :)

**Comment by skyshader** [comment]
Alright. For initials we will go with social login. Let's begin with Login with Google as this course is powered by Google :stuck_out_tongue: @sounak07 / @drenther anyone wants to take this up?

**Comment by sounak07** [comment]
If we do facebook/google login we need a google account for Creating the Google App, Client ID, and Client Secret.....do consider that.

**Comment by drenther** [comment]
@skyshader I don't mind going with localStorage. Glad we know what we need to do to use localStorage properly. And about the social login how do we go about with API Keys handling?

**Comment by skyshader** [comment]
@drenther you have any thoughts on this?

**Comment by sounak07** [comment]
I think using a common key is better and we can always hide it using environment variables created from the terminal.

**Comment by drenther** [comment]
@sounak07 But if we have a common key, how do suggest we share it along? Because as you said yourself we won't commit the .env file

**Comment by skyshader** [comment]
@sounak07 and @drenther we can see if we can generate a basic key that would have limited access available. If that is possible, we will share a .env.example file which will contain that basic api key with limited access.

For proper access we suggest you generate your own api key and we will generate a key that we use for the production environment.

**Comment by sounak07** [comment]
The moderators can choose whomever they want to give access to the key and DM them to share the key i guess.......but that's my opinion, I would like to hear what all of you guys think about this

**Comment by drenther** [comment]
Both have their pros and cons (as with everything I guess). Whatever the moderators choose I guess.

**Comment by SevenSinS02** [comment]
@skyshader The whole point of using cookies to store JWT is to prevent the token from being accessed by any scripts. With local storage, it's way easier to steal tokens. Also, web storage doesn't really adhere to any secure standard for transportation of tokens. With cookies having set `secure: true`  we make sure that the cookies are always sent over HTTPS.
If you're worried about CSRF attacks, you can always use a CSRF token.
However, as someone already mentioned above it's not a top priority to get the most secure app right now.

**Comment by drenther** [comment]
@SevenSinS02 Exactly the point. But, localStorage for the case here I guess. As it will be way simpler than the "Double Submit Cookie" implementation.

**Comment by skyshader** [comment]
@SevenSinS02 I do understand your's and @drenther 's point. And yeah it's not top priority to get the most secure app right now. But we will try to manage the 2 main things that could result in XSS: user's input and any such libraries that might access localstorage. Am I missing anything here?

**Comment by SevenSinS02** [comment]
@drenther I totally understand. 
@sounak07 Since it's only a social authentication, it would remain same throughout any app (at least on the front end).  There would be a difference only in the way the authentication is handled in the backend; which raises a question as to where the authentication is being handled - on the client side or the server side? 
Handling on the client side would be way simpler but, if I'm not mistaken would increase the app size as it would require an SDK. 
Handling on the server side is a little bit trickier but much more secure and keeps the app size relatively smaller.

**Comment by skyshader** [comment]
Umm. That was my initial thought but since social logins really ease the process for users using our app, hence orientation is towards social login a bit more.

**Comment by anurag-majumdar** [comment]
I feel its a good idea to implement the local login first. Although OAuth based logins are really popular with Fb and Google logins. I have used all these techniques before in some of my side projects and as sevensins  mentioned, the sdk for fb and google is also coming into the picture for loading of the app initally at client side.
I have implemented this feature from ground up and will share the flow with you guys.
I can contribute to the full authentication part for implementation of local and social logins.

**Comment by skyshader** [comment]
Guys! Let's limit our conversation on this thread. It gets overwhelming for people to go though the comments here. Let's start with basic JWT auth for now and let's use passport for that so it would be easier to add other strategies in future. Also, let's use localstorage to store the token.

As this is just a backend task for now, we would need to test it via postman only.

**Comment by anurag-majumdar** [comment]
Good call skyshader, I would like to note one thing by saying that it will be way easier to use just only bcrypt and jwt for normal sign in than passport. For jwt we can use passport-jwt library but for password comparing and setting in db we can directly use bcrypt for that.
Code for it will be really simple. I have implemented the same before too.

**Comment by anurag-majumdar** [comment]
If you guys want to use social logins with google and facebook we need to get the api key and client secret. Which will be handled by the moderator or co-moderators for setup so that we can use the same.

**Comment by twishasaraiya** [comment]
I think the contributors should generate their own keys for development purpose and we can have a common key for production purpose. Since many people may be new to this I want someone to take up the task of documenting the whole process of setup so that it would be easy for a newbie too or may provide a link to some article that explains it well.

**Comment by Rohanhacker** [comment]
can I work on this ?

**Comment by highskillzz** [comment]
Just a question, why would a game need authentication?

**Comment by danivijay** [comment]
@sounak07 is currently working on it.

**Comment by Rohanhacker** [comment]
@danivijay Please assign this issue to him if he is working on it

**Comment by danivijay** [comment]
I'm afraid that is not possible @Rohanhacker, assignee list is limited for now.

**Comment by Rohanhacker** [comment]
@danivijay one person will be working on a particular issue at a time right ?? You just have to assign one person ??

**Comment by gpalsingh** [comment]
Is this issue solved? I don't see the pull request that fixes it.

**Comment by danivijay** [comment]
1. https://github.com/UdacityMobileWebScholarship/guess-quote/pull/13 - merged
2. https://github.com/UdacityMobileWebScholarship/guess-quote/pull/25 - under progress
@gpalsingh
